// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-replace/gulp-replace.d.ts
declare module "gulp-replace" {
    interface Options {
        skipBinary?: boolean;
    }

    interface Replacer {
      (match: string): string
    }

    function replace(pattern: string, replacement: string | Replacer, opts?: Options): NodeJS.ReadWriteStream;
    function replace(pattern: RegExp, replacement: string | Replacer, opts?: Options): NodeJS.ReadWriteStream;

    namespace replace {}

    export = replace;
}