// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/gulp-rev-replace/gulp-rev-replace.d.ts
declare module 'gulp-rev-replace' {
  namespace revReplace {
    interface Options {
      canonicalUris?: boolean;
      replaceInExtensions?: Array<string>;
      prefix?: string;
      manifest?: NodeJS.ReadWriteStream;
      modifyUnreved?: Function;
      modifyReved?: Function;
    }
  }

  function revReplace(options?: revReplace.Options): NodeJS.ReadWriteStream;

  export = revReplace;
}